apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gputrackers.suse.tests.dev
spec:
  group: suse.tests.dev
  scope: Cluster
  names:
    plural: gputrackers
    singular: gputracker
    kind: GPUTracker
    shortNames:
      - gputrack
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            gpu_nodes:
              type: string
