apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-tracker-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["suse.tests.dev"]
    resources: ["gputrackers"]
    verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-tracker-rolebinding
subjects:
  - kind: ServiceAccount
    name: gpu-tracker-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: gpu-tracker-role
  apiGroup: rbac.authorization.k8s.io
